### ISSUE TITLE
upload is not a function

### ISSUE THREAD

**Issue by hmit208** [GoogleCloudPlatform/gcs-resumable-upload#78]
i'm sorry if my question is so stupid
i've tried to use this module. It worked on power shell but when i created the .js file like your example, it didn't work and returned that "upload is not a function"
`
var upload = require('gcs-resumable-upload');
var fs = require('fs');

fs.createReadStream('titanic.mov')
    .pipe(upload({ bucket: 'upload-bucket208', file: 'titanic.mov' }))
    .on('finish', function () {
        // Uploaded!
    });
`

>     .pipe(upload({ bucket: 'upload-bucket208', file: 'titanic.mov' }))          ^TypeError: upload is not a function   at Object.<anonymous> (D:\xampp\htdocs\gcs-resumable-upload\test.js:5:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by JustinBeckwith** [comment]
Greetings!  Apologies, the docs are a little out of date.  To import the module please use:

```js
const {upload} = require('gcs-resumable-upload');
```

We have a PR to update the docs in #79.  Hope this helps!
