### ISSUE TITLE
Get the system tests passing

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/gcs-resumable-upload#87]
Right now they're failing with a permissions issue on the test bucket:
https://circleci.com/gh/GoogleCloudPlatform/gcs-resumable-upload/899

@stephenplusplus I kinda forget how all this is set up 😆

**Comment by stephenplusplus** [comment]
Done! I just had to remove the `BUCKET_NAME` env var in Circle.
